### ISSUE TITLE
'enabled?' - keys at depth hidden by key with same name higher up

### ISSUE THREAD

**Issue by ArcticSnowman** [mssola/cconfig#7]
Ok think I found the issue in 
https://github.com/mssola/cconfig/blob/master/lib/cconfig/hash_utils.rb#L35-L43

```
      def enabled?(feature)
        cur   = self
        parts = feature.split(".")

        parts.each do |part|
          cur = cur[part]
          return false if !cur || cur.empty?
          return true  if cur.key?("enabled") && cur["enabled"].eql?(true)
        end

````
The above is a recursive function that splits the key on '.' and checks each level of an 'enabled' key

So take the config 

```
delete:
  enabled: true
  garbage_collector:
    enabled: false
```

Calling `APP_CONFIG.enabled?('delete.garbage_collector')` , the code will check for the key 'delete.enabled' first before looking at 'delete.garbage_collector.enabled', so returning true regardless of the value deeper in..

Related to https://github.com/SUSE/Portus/issues/2015

**Comment by ArcticSnowman** [comment]
Making this modification should fix it

```
      def enabled?(feature)
        cur   = self
        parts = feature.split(".")

        parts.each do |part|
          cur = cur[part]
          return false if !cur || cur.empty?
        end

        return true  if cur.key?("enabled") && cur["enabled"].eql?(true)

        false
      end

```

**Comment by mssola** [comment]
Thanks @ArcticSnowman a lot for your feedback. I was not available last week, and so it took me a while to reply. I've taken your proposal but changed it a bit :+1: I'll release a patch-level release of `cconfig` as soon as possible so Portus can benefit from these fixes.

**Comment by ArcticSnowman** [comment]
Happy to help...
